samples:                           "samples.csv"

trimmomatic:
    environment:                   "../envs/trimmomatic.yaml"
    threads:                       4
    adapters:                      "db/adapters/adapters.fa"
sortmerna:
    environment:                   "../envs/sortmerna.yaml"
    aantal_alignments:             1
    aantal_best:                   1
    paired_optie:                  "paired_in"
fastQC:
    environment:                   "../envs/fastqc.yaml"
    threads:                       4
trinity:
    environment:                   "../envs/trinity.yaml"
    threads:                       4
trinity-assemble:
    max_memory:                    "4G"
    min_kmer_cov:                  1
trinity-DE:
    P_cutoff:                      0.05
    fold_change:                   1.0
    pca_components:                3
mtrans-smk-hs:
    environment:                   "../envs/mtrans-smk-hs.yaml"
