samples:                           "samples.csv"

trimmomatic:
    environment:                   "../envs/trimmomatic.yaml"
    threads:                       4
fastQC:
    environment:                   "../envs/fastqc.yaml"
    threads:                       4
trinity:
    environment:                   "../envs/trinity.yaml"
    threads:                       4
trinity-assemble:
    max_memory:                    "16G"
    min_kmer_cov:                  1
mtrans-smk-hs:
    environment:                   "../envs/mtrans-smk-hs.yaml"
