samples:                           "samples.csv"

trimmomatic:
    environment:                   "../envs/trimmomatic.yaml"
    threads:                       4
    adapters:                      "db/adapters/adapters.fa"
fastQC:
    environment:                   "../envs/fastqc.yaml"
    threads:                       4
trinity:
    environment:                   "../envs/trinity.yaml"
    threads:                       4
trinity-assemble:
    max_memory:                    "16G"
    min_kmer_cov:                  1
trinity-DE:
    P_cutoff:                      0.01
    fold_change:                   1.0
    pca_components:                3
mtrans-smk-hs:
    environment:                   "../envs/mtrans-smk-hs.yaml"
