samples:                            "samples.csv"

general:
    environment:                    "../envs/general.yaml"
trimmomatic:
    environment:                    "../envs/trimmomatic.yaml"
    threads:                    4
    adapters:                       "db/adapters/adapters.fa"
sortmerna:
    environment:                    "../envs/sortmerna.yaml"
    aantal_alignments:              1
    aantal_best:                    1
    paired_optie:                   "paired_in"
    ref_database:                   "fast"
    threads:                        4
    max_memory:                     6000
fastQC:
    environment:                    "../envs/fastqc.yaml"
    threads:                        4
trinity:
    environment:                    "../envs/trinity.yaml"
    threads:                        32
trinity-assemble:
    max_memory:                     "120G"
    min_kmer_cov:                   1
trinity-DE:
    P_cutoff:                       0.05
    fold_change:                    1.0
    pca_components:                 3
interproscan:
    environment:                    "../envs/interproscan.yaml"
    database:                       ""
    analyses:
        - ProSiteProfiles
        - Pfam
        - Gene3D
        - PANTHER
        - PIRSF

