$schema:                              "http://json-schema.org/draft-07/schema#"

description:                          snakemake configuration file

type:                                 object

properties:

    samples:
        type:                         string
        default:                      "samples.csv"

    trimmomatic:
        type:                         object
        properties:
            environment:
                type:                 string
                default:              "../envs/trimmomatic.yaml"
            threads:
                type:                 number
                default:              4

